import oracledb
import os
from dotenv import load_dotenv

load_dotenv()

def apply_sala_sesion():
    print("Connecting to Oracle database...")
    connection = oracledb.connect(
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        dsn=f"{os.getenv('DB_HOST')}:{os.getenv('DB_PORT', '1521')}/{os.getenv('DB_SERVICE_NAME')}"
    )
    cursor = connection.cursor()

    sqls = [
        # Mensajes de Chat
        """
        CREATE TABLE mensajes_sesion (
            id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sesion_id           NUMBER          NOT NULL,
            remitente_id        NUMBER          NOT NULL,
            mensaje             VARCHAR2(4000)  NOT NULL,
            fecha_envio         TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT fk_msg_sesion FOREIGN KEY (sesion_id) REFERENCES sesiones_mentoria (id) ON DELETE CASCADE,
            CONSTRAINT fk_msg_remitente FOREIGN KEY (remitente_id) REFERENCES cuentas (id) ON DELETE CASCADE
        )
        """,
        # Recursos
        """
        CREATE TABLE recursos_sesion (
            id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sesion_id           NUMBER          NOT NULL,
            subido_por          NUMBER          NOT NULL,
            nombre_archivo      VARCHAR2(500)   NOT NULL,
            url_archivo         VARCHAR2(1000)  NOT NULL,
            fecha_subida        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT fk_rec_sesion FOREIGN KEY (sesion_id) REFERENCES sesiones_mentoria (id) ON DELETE CASCADE,
            CONSTRAINT fk_rec_subido FOREIGN KEY (subido_por) REFERENCES cuentas (id) ON DELETE CASCADE
        )
        """,
        # Reportes
        """
        CREATE TABLE reportes_sesion (
            id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sesion_id           NUMBER          NOT NULL,
            reportador_id       NUMBER          NOT NULL,
            descripcion         VARCHAR2(4000)  NOT NULL,
            estado              VARCHAR2(20)    DEFAULT 'pendiente' NOT NULL,
            fecha_creacion      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT ck_rep_estado CHECK (estado IN ('pendiente', 'revisado', 'resuelto')),
            CONSTRAINT fk_rep_sesion FOREIGN KEY (sesion_id) REFERENCES sesiones_mentoria (id) ON DELETE CASCADE,
            CONSTRAINT fk_rep_reportador FOREIGN KEY (reportador_id) REFERENCES cuentas (id) ON DELETE CASCADE
        )
        """,
        # Registrar tablas en tablas_sistema
        "INSERT INTO tablas_sistema (nombre) VALUES ('mensajes_sesion')",
        "INSERT INTO tablas_sistema (nombre) VALUES ('recursos_sesion')",
        "INSERT INTO tablas_sistema (nombre) VALUES ('reportes_sesion')"
    ]

    for sql in sqls:
        try:
            print(f"Executing: {sql[:50]}...")
            cursor.execute(sql)
            connection.commit()
            print("Success.")
        except oracledb.DatabaseError as e:
            error, = e.args
            if error.code == 955: # name is already used by an existing object
                print("Table already exists. Skipping.")
            elif error.code == 1: # unique constraint (tablas_sistema)
                print("Already registered in tablas_sistema. Skipping.")
            else:
                print(f"Error: {e}")

    # Triggers
    triggers = [
        """
        CREATE OR REPLACE TRIGGER trg_audit_mensajes
        AFTER INSERT OR UPDATE OR DELETE ON mensajes_sesion
        FOR EACH ROW
        DECLARE
            v_accion VARCHAR2(10);
            v_cuenta_id NUMBER := NULL;
        BEGIN
            IF INSERTING THEN v_accion := 'crear';
            ELSIF UPDATING THEN v_accion := 'actualizar';
            ELSE v_accion := 'eliminar';
            END IF;
            
            BEGIN
                v_cuenta_id := TO_NUMBER(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'));
            EXCEPTION WHEN OTHERS THEN
                v_cuenta_id := NULL;
            END;

            INSERT INTO historial_cambios (tabla_id, registro_id, accion, descripcion, detalles_json, cuenta_id, ip_origen)
            VALUES (
                (SELECT id FROM tablas_sistema WHERE nombre = 'mensajes_sesion'),
                NVL(:NEW.id, :OLD.id),
                v_accion,
                'Auditoría automática de mensajes',
                JSON_OBJECT('mensaje' VALUE NVL(:NEW.mensaje, :OLD.mensaje)),
                v_cuenta_id,
                SYS_CONTEXT('USERENV', 'CLIENT_INFO')
            );
        END;
        """,
        """
        CREATE OR REPLACE TRIGGER trg_audit_recursos
        AFTER INSERT OR UPDATE OR DELETE ON recursos_sesion
        FOR EACH ROW
        DECLARE
            v_accion VARCHAR2(10);
            v_cuenta_id NUMBER := NULL;
        BEGIN
            IF INSERTING THEN v_accion := 'crear';
            ELSIF UPDATING THEN v_accion := 'actualizar';
            ELSE v_accion := 'eliminar';
            END IF;
            
            BEGIN
                v_cuenta_id := TO_NUMBER(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'));
            EXCEPTION WHEN OTHERS THEN
                v_cuenta_id := NULL;
            END;

            INSERT INTO historial_cambios (tabla_id, registro_id, accion, descripcion, detalles_json, cuenta_id, ip_origen)
            VALUES (
                (SELECT id FROM tablas_sistema WHERE nombre = 'recursos_sesion'),
                NVL(:NEW.id, :OLD.id),
                v_accion,
                'Auditoría automática de recursos',
                JSON_OBJECT('nombre_archivo' VALUE NVL(:NEW.nombre_archivo, :OLD.nombre_archivo)),
                v_cuenta_id,
                SYS_CONTEXT('USERENV', 'CLIENT_INFO')
            );
        END;
        """,
        """
        CREATE OR REPLACE TRIGGER trg_audit_reportes
        AFTER INSERT OR UPDATE OR DELETE ON reportes_sesion
        FOR EACH ROW
        DECLARE
            v_accion VARCHAR2(10);
            v_cuenta_id NUMBER := NULL;
        BEGIN
            IF INSERTING THEN v_accion := 'crear';
            ELSIF UPDATING THEN v_accion := 'actualizar';
            ELSE v_accion := 'eliminar';
            END IF;
            
            BEGIN
                v_cuenta_id := TO_NUMBER(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'));
            EXCEPTION WHEN OTHERS THEN
                v_cuenta_id := NULL;
            END;

            INSERT INTO historial_cambios (tabla_id, registro_id, accion, descripcion, detalles_json, cuenta_id, ip_origen)
            VALUES (
                (SELECT id FROM tablas_sistema WHERE nombre = 'reportes_sesion'),
                NVL(:NEW.id, :OLD.id),
                v_accion,
                'Auditoría automática de reportes',
                JSON_OBJECT('estado' VALUE NVL(:NEW.estado, :OLD.estado)),
                v_cuenta_id,
                SYS_CONTEXT('USERENV', 'CLIENT_INFO')
            );
        END;
        """
    ]

    for trg in triggers:
        try:
            print(f"Creating trigger...")
            cursor.execute(trg)
            connection.commit()
        except oracledb.DatabaseError as e:
            print(f"Trigger error: {e}")
            
    cursor.execute("SELECT line, position, text FROM user_errors WHERE name IN ('TRG_AUDIT_MENSAJES', 'TRG_AUDIT_RECURSOS', 'TRG_AUDIT_REPORTES')")
    errors = cursor.fetchall()
    if errors:
        print("TRIGGER COMPILATION ERRORS:")
        for err in errors:
            print(err)
    else:
        print("Triggers compiled successfully.")

    cursor.close()
    connection.close()

if __name__ == "__main__":
    apply_sala_sesion()
